/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eric.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MyRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -924659274939759343L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyRecord\",\"namespace\":\"com.eric.avro\",\"fields\":[{\"name\":\"timestamp_with_logical_type\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"timestamp_no_logical_type\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MyRecord> ENCODER =
      new BinaryMessageEncoder<MyRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MyRecord> DECODER =
      new BinaryMessageDecoder<MyRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MyRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MyRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MyRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MyRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MyRecord from a ByteBuffer. */
  public static MyRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public org.joda.time.DateTime timestamp_with_logical_type;
  @Deprecated public long timestamp_no_logical_type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MyRecord() {}

  /**
   * All-args constructor.
   * @param timestamp_with_logical_type The new value for timestamp_with_logical_type
   * @param timestamp_no_logical_type The new value for timestamp_no_logical_type
   */
  public MyRecord(org.joda.time.DateTime timestamp_with_logical_type, java.lang.Long timestamp_no_logical_type) {
    this.timestamp_with_logical_type = timestamp_with_logical_type;
    this.timestamp_no_logical_type = timestamp_no_logical_type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return timestamp_with_logical_type;
    case 1: return timestamp_no_logical_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      TIMESTAMP_CONVERSION,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: timestamp_with_logical_type = (org.joda.time.DateTime)value$; break;
    case 1: timestamp_no_logical_type = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'timestamp_with_logical_type' field.
   * @return The value of the 'timestamp_with_logical_type' field.
   */
  public org.joda.time.DateTime getTimestampWithLogicalType() {
    return timestamp_with_logical_type;
  }

  /**
   * Sets the value of the 'timestamp_with_logical_type' field.
   * @param value the value to set.
   */
  public void setTimestampWithLogicalType(org.joda.time.DateTime value) {
    this.timestamp_with_logical_type = value;
  }

  /**
   * Gets the value of the 'timestamp_no_logical_type' field.
   * @return The value of the 'timestamp_no_logical_type' field.
   */
  public java.lang.Long getTimestampNoLogicalType() {
    return timestamp_no_logical_type;
  }

  /**
   * Sets the value of the 'timestamp_no_logical_type' field.
   * @param value the value to set.
   */
  public void setTimestampNoLogicalType(java.lang.Long value) {
    this.timestamp_no_logical_type = value;
  }

  /**
   * Creates a new MyRecord RecordBuilder.
   * @return A new MyRecord RecordBuilder
   */
  public static com.eric.avro.MyRecord.Builder newBuilder() {
    return new com.eric.avro.MyRecord.Builder();
  }

  /**
   * Creates a new MyRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MyRecord RecordBuilder
   */
  public static com.eric.avro.MyRecord.Builder newBuilder(com.eric.avro.MyRecord.Builder other) {
    return new com.eric.avro.MyRecord.Builder(other);
  }

  /**
   * Creates a new MyRecord RecordBuilder by copying an existing MyRecord instance.
   * @param other The existing instance to copy.
   * @return A new MyRecord RecordBuilder
   */
  public static com.eric.avro.MyRecord.Builder newBuilder(com.eric.avro.MyRecord other) {
    return new com.eric.avro.MyRecord.Builder(other);
  }

  /**
   * RecordBuilder for MyRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyRecord>
    implements org.apache.avro.data.RecordBuilder<MyRecord> {

    private org.joda.time.DateTime timestamp_with_logical_type;
    private long timestamp_no_logical_type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.eric.avro.MyRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.timestamp_with_logical_type)) {
        this.timestamp_with_logical_type = data().deepCopy(fields()[0].schema(), other.timestamp_with_logical_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp_no_logical_type)) {
        this.timestamp_no_logical_type = data().deepCopy(fields()[1].schema(), other.timestamp_no_logical_type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MyRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.eric.avro.MyRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.timestamp_with_logical_type)) {
        this.timestamp_with_logical_type = data().deepCopy(fields()[0].schema(), other.timestamp_with_logical_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp_no_logical_type)) {
        this.timestamp_no_logical_type = data().deepCopy(fields()[1].schema(), other.timestamp_no_logical_type);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'timestamp_with_logical_type' field.
      * @return The value.
      */
    public org.joda.time.DateTime getTimestampWithLogicalType() {
      return timestamp_with_logical_type;
    }

    /**
      * Sets the value of the 'timestamp_with_logical_type' field.
      * @param value The value of 'timestamp_with_logical_type'.
      * @return This builder.
      */
    public com.eric.avro.MyRecord.Builder setTimestampWithLogicalType(org.joda.time.DateTime value) {
      validate(fields()[0], value);
      this.timestamp_with_logical_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp_with_logical_type' field has been set.
      * @return True if the 'timestamp_with_logical_type' field has been set, false otherwise.
      */
    public boolean hasTimestampWithLogicalType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'timestamp_with_logical_type' field.
      * @return This builder.
      */
    public com.eric.avro.MyRecord.Builder clearTimestampWithLogicalType() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp_no_logical_type' field.
      * @return The value.
      */
    public java.lang.Long getTimestampNoLogicalType() {
      return timestamp_no_logical_type;
    }

    /**
      * Sets the value of the 'timestamp_no_logical_type' field.
      * @param value The value of 'timestamp_no_logical_type'.
      * @return This builder.
      */
    public com.eric.avro.MyRecord.Builder setTimestampNoLogicalType(long value) {
      validate(fields()[1], value);
      this.timestamp_no_logical_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp_no_logical_type' field has been set.
      * @return True if the 'timestamp_no_logical_type' field has been set, false otherwise.
      */
    public boolean hasTimestampNoLogicalType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp_no_logical_type' field.
      * @return This builder.
      */
    public com.eric.avro.MyRecord.Builder clearTimestampNoLogicalType() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MyRecord build() {
      try {
        MyRecord record = new MyRecord();
        record.timestamp_with_logical_type = fieldSetFlags()[0] ? this.timestamp_with_logical_type : (org.joda.time.DateTime) defaultValue(fields()[0], record.getConversion(0));
        record.timestamp_no_logical_type = fieldSetFlags()[1] ? this.timestamp_no_logical_type : (java.lang.Long) defaultValue(fields()[1], record.getConversion(1));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MyRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<MyRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MyRecord>
    READER$ = (org.apache.avro.io.DatumReader<MyRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
